# Generated by Django 5.2.4 on 2025-07-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_user', models.IntegerField()),
                ('id_clinica', models.IntegerField()),
                ('tipo', models.CharField(max_length=25)),
                ('prioridade', models.IntegerField()),
                ('caminho', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
