# Generated by Django 5.2.4 on 2025-07-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cod_executor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='situtacao',
            field=models.CharField(default='Aberto', max_length=30),
        ),
    ]
