# Generated by Django 5.2.4 on 2025-07-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_cod_executor_task_situtacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='cod_executor',
            new_name='cod_dev',
        ),
    ]
