# Generated by Django 5.2.4 on 2025-07-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_cod_executor_task_cod_dev'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='situtacao',
            new_name='situacao',
        ),
    ]
